package xyz.kmahyyg.eshopdemo.model;
import java.io.Serializable;
import java.math.BigDecimal;
import lombok.Data;

/**
 * null
 * @TableName sys_items
 */
@Data
public class SysItems implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String cid;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String itemid;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String name;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private BigDecimal price;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Boolean status;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String image;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String descr;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String shopown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_items
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysItems other = (SysItems) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getItemid() == null ? other.getItemid() == null : this.getItemid().equals(other.getItemid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getImage() == null ? other.getImage() == null : this.getImage().equals(other.getImage()))
            && (this.getDescr() == null ? other.getDescr() == null : this.getDescr().equals(other.getDescr()))
            && (this.getShopown() == null ? other.getShopown() == null : this.getShopown().equals(other.getShopown()));
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getItemid() == null) ? 0 : getItemid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
        result = prime * result + ((getDescr() == null) ? 0 : getDescr().hashCode());
        result = prime * result + ((getShopown() == null) ? 0 : getShopown().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cid=").append(cid);
        sb.append(", itemid=").append(itemid);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", status=").append(status);
        sb.append(", image=").append(image);
        sb.append(", descr=").append(descr);
        sb.append(", shopown=").append(shopown);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}