package xyz.kmahyyg.eshopdemo.model;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName sys_item_cates
 */
@Data
public class SysItemCates implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String name;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_item_cates
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysItemCates other = (SysItemCates) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()));
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", cid=").append(cid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}