package xyz.kmahyyg.eshopdemo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName sys_orders
 */
@Data
public class SysOrders implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String oid;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Boolean status;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String items;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String uid;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private BigDecimal finalprice;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Date gentime;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Date paidtime;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Date donetime;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Date refundtime;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Boolean paymentid;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Boolean deliveryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_orders
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysOrders other = (SysOrders) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOid() == null ? other.getOid() == null : this.getOid().equals(other.getOid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getItems() == null ? other.getItems() == null : this.getItems().equals(other.getItems()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getFinalprice() == null ? other.getFinalprice() == null : this.getFinalprice().equals(other.getFinalprice()))
            && (this.getGentime() == null ? other.getGentime() == null : this.getGentime().equals(other.getGentime()))
            && (this.getPaidtime() == null ? other.getPaidtime() == null : this.getPaidtime().equals(other.getPaidtime()))
            && (this.getDonetime() == null ? other.getDonetime() == null : this.getDonetime().equals(other.getDonetime()))
            && (this.getRefundtime() == null ? other.getRefundtime() == null : this.getRefundtime().equals(other.getRefundtime()))
            && (this.getPaymentid() == null ? other.getPaymentid() == null : this.getPaymentid().equals(other.getPaymentid()))
            && (this.getDeliveryid() == null ? other.getDeliveryid() == null : this.getDeliveryid().equals(other.getDeliveryid()));
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOid() == null) ? 0 : getOid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getItems() == null) ? 0 : getItems().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getFinalprice() == null) ? 0 : getFinalprice().hashCode());
        result = prime * result + ((getGentime() == null) ? 0 : getGentime().hashCode());
        result = prime * result + ((getPaidtime() == null) ? 0 : getPaidtime().hashCode());
        result = prime * result + ((getDonetime() == null) ? 0 : getDonetime().hashCode());
        result = prime * result + ((getRefundtime() == null) ? 0 : getRefundtime().hashCode());
        result = prime * result + ((getPaymentid() == null) ? 0 : getPaymentid().hashCode());
        result = prime * result + ((getDeliveryid() == null) ? 0 : getDeliveryid().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", oid=").append(oid);
        sb.append(", status=").append(status);
        sb.append(", items=").append(items);
        sb.append(", uid=").append(uid);
        sb.append(", finalprice=").append(finalprice);
        sb.append(", gentime=").append(gentime);
        sb.append(", paidtime=").append(paidtime);
        sb.append(", donetime=").append(donetime);
        sb.append(", refundtime=").append(refundtime);
        sb.append(", paymentid=").append(paymentid);
        sb.append(", deliveryid=").append(deliveryid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}