package xyz.kmahyyg.eshopdemo.model;
import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName sys_user_cart
 */
@Data
public class SysUserCart implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String uid;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String items;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_cart
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysUserCart other = (SysUserCart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getItems() == null ? other.getItems() == null : this.getItems().equals(other.getItems()));
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getItems() == null) ? 0 : getItems().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", items=").append(items);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}