package xyz.kmahyyg.eshopdemo.model;
import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName sys_users
 */
@Data
public class SysUsers implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String uid;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Long phone;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String password;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String role;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String avatar;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Boolean preferpayment;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private Boolean preferdelivery;

    /**
     * 
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_users
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysUsers other = (SysUsers) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getPreferpayment() == null ? other.getPreferpayment() == null : this.getPreferpayment().equals(other.getPreferpayment()))
            && (this.getPreferdelivery() == null ? other.getPreferdelivery() == null : this.getPreferdelivery().equals(other.getPreferdelivery()))
            && (this.getAddr() == null ? other.getAddr() == null : this.getAddr().equals(other.getAddr()));
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getPreferpayment() == null) ? 0 : getPreferpayment().hashCode());
        result = prime * result + ((getPreferdelivery() == null) ? 0 : getPreferdelivery().hashCode());
        result = prime * result + ((getAddr() == null) ? 0 : getAddr().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-02-06 00:30:33
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", uid=").append(uid);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", role=").append(role);
        sb.append(", avatar=").append(avatar);
        sb.append(", preferpayment=").append(preferpayment);
        sb.append(", preferdelivery=").append(preferdelivery);
        sb.append(", addr=").append(addr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}